### ISSUE TITLE
Error when i want to install

### ISSUE THREAD

**Issue by Wihoui** [Smatnemo/pibooth-picamera2#1]
Hello,
i want to test your plugin for pibooth, but i have an error when i want to install it.
What version of raspberry OS i have to use ?
And for what version of pibooth it's work ?

Because i have an error when i want to install plugin.

Thank you

**Comment by Smatnemo** [comment]
> Hello, i want to test your plugin for pibooth, but i have an error when i want to install it. What version of raspberry OS i have to use ? And for what version of pibooth it's work ?
> 
> Because i have an error when i want to install plugin.
> 
> Thank you

Can you describe the error, or post a copy of the log file?
I used pibooth 2.0.8 and raspberry pi OS bookworm.

**Comment by Wihoui** [comment]
Sorry, i was on an other OS.
With bookworm, it's looks work.
But my pi crash all the time, what is your version of pi ? V5 ?
Thank you

**Comment by Smatnemo** [comment]
Mine is raspberry pi 5 running bookworm. Do you think the reason for the crash is related to pibooth or the plugin?
I have not experienced any crash using mine.

**Comment by Wihoui** [comment]
Mine is a 3 model B, i think is the reason maybe...
is-it necessary to install it on virtual environment ?

**Comment by Smatnemo** [comment]
It is recommended on bookworm to use virtual environments. However, I have not tested on raspberry pi 3. Try using a virtual environment.
Let me know if that helps.

**Comment by Smatnemo** [comment]
> Mine is a 3 model B, i think is the reason maybe... is-it necessary to install it on virtual environment ?

Unless you still have complaints, I am going to go ahead and close this issue.

**Comment by Wihoui** [comment]
The app crash when i am on fullscreen mode. I don't have this problem on picamera with out you plug-in.
Maybe the memory by the New cam  IS more important

**Comment by Smatnemo** [comment]
I have used pygame to render the preview. Because pygame uses software rendering and not gpu, the rendering could be taking up a lot of cpu power. Try reducing the resolution and test it again.
I will eventually look for a way to offload the processing to gpu in a later version.

One way to be sure is to use htop to monitor the CPU.
