### ISSUE TITLE
can't install 

### ISSUE THREAD

**Issue by alexismorsilli** [Smatnemo/pibooth-picamera2#2]
Hello , i have this issue when i try to install : (pi 5 , bookworm )

pip3 install pibooth-picamera2
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pibooth-picamera2
  Using cached pibooth_picamera2-1.0.1-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: pibooth>=2.0.0 in /home/pibooth/venv/lib/python3.11/site-packages (from pibooth-picamera2) (2.0.8)
INFO: pip is looking at multiple versions of pibooth-picamera2 to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement picamera2==0.3.19 (from pibooth-picamera2) (from versions: 0.1.1, 0.2.1, 0.2.2, 0.2.3, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.3.10, 0.3.11, 0.3.12, 0.3.14, 0.3.16, 0.3.17, 0.3.18, 0.3.21, 0.3.22)
ERROR: No matching distribution found for picamera2==0.3.19

i try to install with and without virtual environnement , both doesn't work .
thanks for help

**Comment by alexismorsilli** [comment]
if you have a solution to use my hq camera with pi 5 bookworm cause i have this issu:  

pibooth                                       
pygame 2.1.2 (SDL 2.26.5, Python 3.11.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
pygame-menu 4.0.7
[ INFO    ] pibooth           : Installed plugins: 
[ INFO    ] pibooth           : Starting the photo booth application on Raspberry pi 5B
[ WARN:0@1.535] global ./modules/videoio/src/cap_gstreamer.cpp (2401) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src0 reported: Cannot identify device '/dev/video0'.
[ WARN:0@1.535] global ./modules/videoio/src/cap_gstreamer.cpp (1356) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0@1.535] global ./modules/videoio/src/cap_gstreamer.cpp (862) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
[ WARN:0@1.535] global ./modules/videoio/src/cap_v4l.cpp (902) open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ WARN:0@1.673] global ./modules/videoio/src/cap_gstreamer.cpp (2401) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src1 reported: Cannot identify device '/dev/video1'.
[ WARN:0@1.673] global ./modules/videoio/src/cap_gstreamer.cpp (1356) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0@1.673] global ./modules/videoio/src/cap_gstreamer.cpp (862) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
[ WARN:0@1.673] global ./modules/videoio/src/cap_v4l.cpp (902) open VIDEOIO(V4L2:/dev/video1): can't open camera by index
[ WARN:0@1.807] global ./modules/videoio/src/cap_gstreamer.cpp (2401) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src2 reported: Failed to allocate required memory.
[ WARN:0@1.808] global ./modules/videoio/src/cap_gstreamer.cpp (1356) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0@1.808] global ./modules/videoio/src/cap_gstreamer.cpp (862) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
[ INFO    ] pibooth           : Configuring OpenCV camera ...
[ WARNING ] pibooth           : No printer found (pycups or pycups-notify not installed)
[ INFO    ] pibooth           : Show picture choice (nothing selected)
[ INFO    ] pibooth           : Show picture choice (1 captures selected)
[ INFO    ] pibooth           : Show preview before next capture
[ ERROR   ] pibooth           : Can not get camera preview image
[ ERROR   ] pibooth           : system='Linux', node='pibooth', release='6.6.51+rpt-rpi-v8', version='#1 SMP PREEMPT Debian 1:6.6.51-1+rpt3 (2024-10-08)', machine='aarch64', processor=''


but it work on my pi 3b+ with bullseye. 

thanks

**Comment by Smatnemo** [comment]
@alexismorsilli Hi, it is recommended that picamera2 library is installed using apt. I must have made a mistake in the setup.py file including version 0.3.19 because it is clearly not included in the list. I will update the README for better instructions and eliminate the requirement. 

As for your hq camera, I will need to know what the camera version is to help. 

This line hear is reporting an issue:
 [ WARN:0@1.535] global ./modules/videoio/src/cap_gstreamer.cpp (2401) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src0 reported: Cannot identify device '/dev/video0'.

**Comment by Smatnemo** [comment]
@alexismorsilli I have updated the plugin and changed the requirements. Can you give it a try and let me know how it goes.

**Comment by alexismorsilli** [comment]
@Smatnemo it works now!! thanks so much for you help!!  so you can add  HQ camera v1.0 test passed :)

**Comment by alexismorsilli** [comment]
@Smatnemo   I notice a fairly significant difference between my pi4 8g under bullseyes and the pi5 with this plugging in terms of the fluidity of the camera. the camera is very fluid on pi4 without the plugin and on bookworm pi5 with the plugin it is very slow. However, I allocated 256 MB to the GPU on the 2 raspberry, and the camera is set to 4056X3040. same configuration on pi4 et 5 , the only difference is the plugin. do you think it is possible to improve fluidity without lowering the quality of the camera and renderings? because otherwise there is no point in switching to a pi5   thanks!!!

**Comment by alexismorsilli** [comment]
here is the logs if it can help: 

pibooth
pygame 2.1.2 (SDL 2.26.5, Python 3.11.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
pygame-menu 4.0.7
[ INFO    ] pibooth           : Installed plugins: picamera2-1.0.2
[ INFO    ] pibooth           : Starting the photo booth application on Raspberry pi 5B
[0:00:36.149897718] [1551]  INFO Camera camera_manager.cpp:325 libcamera v0.3.2+27-7330f29b
[0:00:36.159517273] [1577]  INFO RPI pisp.cpp:695 libpisp version v1.0.7 28196ed6edcf 29-08-2024 (16:42:16)
[0:00:36.176528255] [1577]  INFO RPI pisp.cpp:1154 Registered camera /base/axi/pcie@120000/rp1/i2c@88000/imx477@1a to CFE device /dev/media0 and ISP device /dev/media1 using PiSP variant BCM2712_C0
[ INFO    ] picamera2.picamera2: Initialization successful.
[ INFO    ] picamera2.picamera2: Camera now open.
[ INFO    ] pibooth           : Use Picamera2 library
[ INFO    ] pibooth           : Connected to printer 'EPSON_XP_4200_Series'
[ INFO    ] pibooth           : Show picture choice (nothing selected)
[ INFO    ] pibooth           : Show picture choice (1 captures selected)
[ INFO    ] pibooth           : Show preview before next capture
[ INFO    ] picamera2.picamera2: Camera configuration has been adjusted!
[0:00:44.265579843] [1551]  INFO Camera camera.cpp:1197 configuring streams: (0) 4056x3040-XBGR8888 (1) 4056x3040-GBRG_PISP_COMP1
[0:00:44.265761213] [1577]  INFO RPI pisp.cpp:1450 Sensor: /base/axi/pcie@120000/rp1/i2c@88000/imx477@1a - Selected sensor format: 4056x3040-SGBRG12_1X12 - Selected CFE format: 4056x3040-PC1g
[ INFO    ] picamera2.picamera2: Configuration successful!
[ INFO    ] picamera2.picamera2: Camera started
[ INFO    ] pibooth           : Take a capture
[ INFO    ] picamera2.picamera2: Camera stopped
[ INFO    ] picamera2.picamera2: Camera configuration has been adjusted!
[0:00:50.903687876] [1588]  INFO Camera camera.cpp:1197 configuring streams: (0) 4056x3040-BGR888 (1) 4056x3040-BGGR_PISP_COMP1
[0:00:50.918728339] [1577]  INFO RPI pisp.cpp:1450 Sensor: /base/axi/pcie@120000/rp1/i2c@88000/imx477@1a - Selected sensor format: 4056x3040-SBGGR12_1X12 - Selected CFE format: 4056x3040-PC1B
[ INFO    ] picamera2.picamera2: Configuration successful!
[ INFO    ] picamera2.picamera2: Camera started
[ INFO    ] picamera2.request : Saved <picamera2.request.Helpers object at 0xc8897670> to file <_io.BytesIO object at 0xc8f9f050>.
[ INFO    ] picamera2.request : Time taken for encode: 257.98846299999667 ms.
[ INFO    ] picamera2.picamera2: Camera stopped
[0:00:52.138581431] [1588]  INFO Camera camera.cpp:1197 configuring streams: (0) 4056x3040-XBGR8888 (1) 4056x3040-GBRG_PISP_COMP1
[0:00:52.148037690] [1577]  INFO RPI pisp.cpp:1450 Sensor: /base/axi/pcie@120000/rp1/i2c@88000/imx477@1a - Selected sensor format: 4056x3040-SGBRG12_1X12 - Selected CFE format: 4056x3040-PC1g
[ INFO    ] picamera2.picamera2: Configuration successful!
[ INFO    ] picamera2.picamera2: Camera started
[ INFO    ] picamera2.picamera2: Camera stopped
[ INFO    ] pibooth           : Sopped preview
[ INFO    ] pibooth           : Saving raw captures
[ INFO    ] pibooth           : Creating the final picture
[ INFO    ] pibooth           : Use OpenCvPictureFactory to create background
[ INFO    ] pibooth           : Use OpenCvPictureFactory to concatenate images
[ INFO    ] pibooth           : Use OpenCvPictureFactory to assemble final image
[ INFO    ] pibooth           : Use OpenCvPictureFactory to draw texts
[ INFO    ] pibooth           : Save image '/home/pibooth/Pictures/pibooth/2024-11-18-22-11-21_pibooth.jpg'
[ INFO    ] pibooth           : Display the final picture
[ INFO    ] picamera2.picamera2: Camera closed successfully.

**Comment by Smatnemo** [comment]
> @Smatnemo I notice a fairly significant difference between my pi4 8g under bullseyes and the pi5 with this plugging in terms of the fluidity of the camera. the camera is very fluid on pi4 without the plugin and on bookworm pi5 with the plugin it is very slow. However, I allocated 256 MB to the GPU on the 2 raspberry, and the camera is set to 4056X3040. same configuration on pi4 et 5 , the only difference is the plugin. do you think it is possible to improve fluidity without lowering the quality of the camera and renderings? because otherwise there is no point in switching to a pi5 thanks!!!

Hi @alexismorsilli It is possible to do so. I will work on that in a later version. The plugin doesn't use the gpu that is why you haven't noticed any difference in performance.

**Comment by alexismorsilli** [comment]
Ok i understand thanks  😊
